name: CI TEST

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: 'inspect source code'
        run: |
          echo "inspecting source code"
          ls -la
      - name: Run tests
        run: |
          echo "Running tests"
          echo "Tests passed"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests"
          echo "Tests passed"
